language: node_js
node_js:
  - '12'

dist: xenial

cache:
  yarn: true
  directories:
    - node_modules
    - .cache

install:
  - yarn install

script:
  - yarn run build

deploy:
  provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  fqdn: r.obin.ch
  on:
    branch: master
