language: node_js
node_js:
 - "12"

cache:
  yarn: true
  directories:
    - node_modules
    - .cache

before_install:
 - apt install xsel make g++

install:
 - yarn install

script:
  - yarn run build

deploy:
  provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
